name: Generate Test Scenario
description: Generate Test Scenario based on variants, lab number, and students' configs

inputs:
  variant_number:
    description: "Variant number"
    required: true
  lab_number:
    description: "Lab number"
    required: true
  wokwi_toml_path:
    description: "Path to wokwi.toml file"
    required: true
  output:
    description: "Output file"
    required: false
    default: "test_scenario.yml"

outputs:
  test_scenario:
    description: "Generated test scenario file path"

runs:
  using: "composite"
  steps:
    - name: Generate Test Scenario
      run: |
        ${{ github.action_path }}/lab${{ inputs.lab_number }}-parser \
          -variant=${{ inputs.variant_number }} \
          -variants-path=${{ github.action_path }}/variants/lab${{ inputs.lab_number }}.yml \
          -wokwi-config=${{ inputs.wokwi_toml_path }} \
          -output=${{ inputs.output }} \
          -root-path=${{ github.action_path }}
        echo "Generated test scenario file: ${{ github.action_path }}"
      shell:  bash
    
    - name: Set output
      id: set_output
      run: |
        echo "test_scenario='${{ inputs.output }}'" >> $GITHUB_OUTPUT
      shell:  bash
