name: Build executables

on:
  push:
    branches: [ main ]
    paths:
        - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build executables
        run: |
            bash build.sh

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: "Update executables"
